export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  it: [
    'Roma', 'Milano', 'Napoli', 'Torino', 'Palermo', 'Genova', 'Bologna', 'Firenze',
    'Bari', 'Catania', 'Venezia', 'Verona', 'Messina', 'Padova', 'Trieste', 'Taranto',
    'Brescia', 'Parma', 'Prato', 'Modena', 'Reggio Calabria', 'Reggio Emilia',
    'Perugia', 'Ravenna', 'Livorno', 'Cagliari', 'Foggia', 'Rimini', 'Salerno',
    'Ferrara', 'Sassari', 'Latina', 'Giugliano in Campania', 'Monza', 'Siracusa',
    'Pescara', 'Bergamo', 'Forlì', 'Trento', 'Vicenza', 'Terni', 'Bolzano',
    'Novara', 'Piacenza', 'Ancona', 'Andria', 'Arezzo', 'Udine', 'Cesena',
    'Lecce', 'Pesaro', 'Alessandria', 'La Spezia', 'Pistoia', 'Catanzaro',
    'Lucca', 'Torre del Greco', 'Brindisi', 'Como', 'Busto Arsizio', 'Marsala',
    'Altamura', 'Sesto San Giovanni', 'Pozzuoli', 'Guidonia Montecelio',
    "Quartu Sant'Elena", 'Castellammare di Stabia', 'Lamezia Terme', 'Ragusa',
    'Cosenza', 'Massa', 'Trapani', 'Crotone', 'Potenza', 'Fiumicino',
    'Cinisello Balsamo', 'Carrara', 'Vittoria', 'Aprilia', 'Manfredonia',
    'Vigevano', 'Legnano', 'Matera', 'Caserta', 'Asti', 'Moncalieri',
    'Acerra', 'Afragola', 'Aversa', 'Portici', 'San Severo', 'Cerignola',
    'Casoria', 'Caltanissetta', 'Treviso', 'Bagheria', 'Gela', 'Carpi',
    'Imola', 'Mazara del Vallo', "Cava de' Tirreni", 'Barletta', 'Olbia',
    'Acireale', 'Molfetta', 'Bitonto', 'San Benedetto del Tronto',
    'Ercolano', 'Scafati', 'Gallarate', 'Faenza', 'Marano di Napoli',
    'Velletri', 'Viterbo', 'Savona', 'Agrigento', 'Corigliano-Rossano',
    'Collegno', 'Sanremo', 'Benevento', 'Avellino', 'Lodi', 'Trani',
    'Teramo', 'Chieti', 'Rovigo', 'Grosseto', 'Siena', 'Varese',
    'Cremona', 'Pavia', 'Mantova', 'Lecco', 'Campobasso', 'Vercelli',
    'Enna', 'Nuoro', 'Oristano', 'Biella', 'Verbania', 'Belluno',
    'Pordenone', 'Gorizia', 'Aosta', 'Rieti', 'Frosinone', 'Isernia',
    'Sondrio', 'Imperia',
  ],
  es: [
    'Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Zaragoza', 'Málaga', 'Murcia',
    'Palma de Mallorca', 'Las Palmas', 'Bilbao', 'Alicante', 'Córdoba', 'Valladolid',
    'Vigo', 'Gijón', 'Hospitalet de Llobregat', 'A Coruña', 'Vitoria-Gasteiz',
    'Granada', 'Elche', 'Oviedo', 'Badalona', 'Cartagena', 'Terrassa', 'Jerez',
    'Sabadell', 'Santa Cruz de Tenerife', 'Pamplona', 'Almería', 'Donostia-San Sebastián',
    'Santander', 'Burgos', 'Castellón', 'Albacete', 'Alcorcón', 'Getafe',
    'Salamanca', 'Logroño', 'Huelva', 'Badajoz', 'Tarragona', 'León',
    'Lleida', 'Marbella', 'Cádiz', 'Jaén', 'Ourense', 'Girona', 'Lugo', 'Toledo',
  ],
  fr: [
    'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Montpellier',
    'Strasbourg', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Saint-Étienne',
    'Toulon', 'Le Havre', 'Grenoble', 'Dijon', 'Angers', 'Nîmes', 'Villeurbanne',
    'Clermont-Ferrand', 'Le Mans', 'Aix-en-Provence', 'Brest', 'Tours', 'Amiens',
    'Limoges', 'Annecy', 'Perpignan', 'Boulogne-Billancourt', 'Metz', 'Besançon',
    'Orléans', 'Rouen', 'Mulhouse', 'Caen', 'Nancy', 'Argenteuil', 'Montreuil',
    'Saint-Denis', 'Roubaix', 'Tourcoing', 'Avignon', 'Dunkerque', 'Poitiers',
    'Pau', 'La Rochelle', 'Calais', 'Cannes', 'Antibes',
  ],
  de: [
    'Berlin', 'Hamburg', 'München', 'Köln', 'Frankfurt am Main', 'Stuttgart',
    'Düsseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Bremen', 'Dresden', 'Hannover',
    'Nürnberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Münster',
    'Mannheim', 'Karlsruhe', 'Augsburg', 'Wiesbaden', 'Mönchengladbach', 'Gelsenkirchen',
    'Aachen', 'Braunschweig', 'Kiel', 'Chemnitz', 'Halle', 'Magdeburg', 'Freiburg',
    'Krefeld', 'Mainz', 'Lübeck', 'Erfurt', 'Oberhausen', 'Rostock', 'Kassel',
    'Hagen', 'Potsdam', 'Saarbrücken', 'Hamm', 'Ludwigshafen', 'Oldenburg',
    'Osnabrück', 'Leverkusen', 'Heidelberg', 'Darmstadt',
  ],
  gb: [
    'London', 'Birmingham', 'Manchester', 'Leeds', 'Glasgow', 'Liverpool',
    'Newcastle', 'Sheffield', 'Bristol', 'Edinburgh', 'Leicester', 'Coventry',
    'Bradford', 'Cardiff', 'Belfast', 'Nottingham', 'Kingston upon Hull', 'Stoke-on-Trent',
    'Wolverhampton', 'Derby', 'Swansea', 'Southampton', 'Plymouth', 'Reading',
    'Luton', 'Aberdeen', 'Northampton', 'Sunderland', 'Norwich', 'Preston',
    'Milton Keynes', 'Brighton', 'Bournemouth', 'Swindon', 'Peterborough',
    'Oxford', 'Cambridge', 'Dundee', 'York', 'Portsmouth', 'Exeter', 'Bath',
    'Ipswich', 'Gloucester', 'Worcester', 'Cheltenham', 'Chester', 'Canterbury',
    'Inverness', 'Stirling',
  ],
  pt: [
    'Lisboa', 'Porto', 'Vila Nova de Gaia', 'Amadora', 'Braga', 'Almada',
    'Funchal', 'Coimbra', 'Setúbal', 'Agualva-Cacém', 'Queluz', 'Aveiro',
    'Évora', 'Faro', 'Guimarães', 'Leiria', 'Viseu', 'Viana do Castelo',
    'Vila Real', 'Bragança', 'Castelo Branco', 'Santarém', 'Portalegre',
    'Ponta Delgada', 'Beja',
  ],
  nl: [
    'Amsterdam', 'Rotterdam', 'Den Haag', 'Utrecht', 'Eindhoven', 'Groningen',
    'Tilburg', 'Almere', 'Breda', 'Nijmegen', 'Arnhem', 'Haarlem', 'Enschede',
    'Haarlemmermeer', 'Amersfoort', 'Apeldoorn', 'Zaanstad', 'Hertogenbosch',
    'Zwolle', 'Zoetermeer', 'Leiden', 'Maastricht', 'Dordrecht', 'Ede', 'Leeuwarden',
  ],
  be: [
    'Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège', 'Bruges', 'Namur',
    'Louvain', 'Mons', 'Malines', 'Aalst', 'Hasselt', 'Courtrai', 'Ostende',
    'Tournai', 'Genk', 'Seraing', 'Roeselare', 'Verviers', 'Mouscron',
  ],
  at: [
    'Wien', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach',
    'Wels', 'Sankt Pölten', 'Dornbirn', 'Wiener Neustadt', 'Steyr', 'Feldkirch',
    'Bregenz', 'Leonding', 'Klosterneuburg', 'Baden', 'Wolfsberg', 'Leoben', 'Traun',
  ],
  ch: [
    'Zürich', 'Genève', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Luzern',
    'St. Gallen', 'Lugano', 'Biel', 'Thun', 'Köniz', 'La Chaux-de-Fonds',
    'Fribourg', 'Schaffhausen', 'Chur', 'Neuchâtel', 'Vernier', 'Sion', 'Uster',
  ],
  pl: [
    'Warszawa', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin',
    'Bydgoszcz', 'Lublin', 'Białystok', 'Katowice', 'Gdynia', 'Częstochowa',
    'Radom', 'Toruń', 'Sosnowiec', 'Rzeszów', 'Kielce', 'Gliwice', 'Olsztyn',
    'Zabrze', 'Bielsko-Biała', 'Bytom', 'Zielona Góra', 'Rybnik', 'Ruda Śląska',
    'Opole', 'Tychy', 'Gorzów Wielkopolski', 'Elbląg',
  ],
  us: [
    'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia',
    'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville',
    'Fort Worth', 'Columbus', 'Charlotte', 'Indianapolis', 'San Francisco',
    'Seattle', 'Denver', 'Washington', 'Nashville', 'Oklahoma City', 'El Paso',
    'Boston', 'Portland', 'Las Vegas', 'Memphis', 'Louisville', 'Baltimore',
    'Milwaukee', 'Albuquerque', 'Tucson', 'Fresno', 'Mesa', 'Sacramento',
    'Atlanta', 'Kansas City', 'Colorado Springs', 'Omaha', 'Raleigh',
    'Miami', 'Minneapolis', 'Tampa', 'New Orleans', 'Cleveland', 'Pittsburgh',
    'Cincinnati', 'St. Louis', 'Orlando', 'Detroit',
  ],
  gr: [
    'Αθήνα', 'Θεσσαλονίκη', 'Πάτρα', 'Ηράκλειο', 'Λάρισα', 'Βόλος',
    'Ιωάννινα', 'Χανιά', 'Χαλκίδα', 'Σέρρες', 'Αλεξανδρούπολη', 'Ξάνθη',
    'Κατερίνη', 'Αγρίνιο', 'Καλαμάτα', 'Καβάλα', 'Ρόδος', 'Κέρκυρα',
    'Τρίκαλα', 'Κομοτηνή',
  ],
  ro: [
    'București', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova',
    'Brașov', 'Galați', 'Ploiești', 'Oradea', 'Brăila', 'Arad', 'Pitești',
    'Sibiu', 'Bacău', 'Târgu Mureș', 'Baia Mare', 'Buzău', 'Botoșani', 'Satu Mare',
  ],
  hr: [
    'Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Slavonski Brod', 'Pula',
    'Karlovac', 'Sisak', 'Varaždin', 'Šibenik', 'Dubrovnik', 'Bjelovar',
    'Vinkovci', 'Velika Gorica', 'Vukovar', 'Koprivnica', 'Đakovo', 'Požega', 'Čakovec',
  ],
  se: [
    'Stockholm', 'Göteborg', 'Malmö', 'Uppsala', 'Linköping', 'Västerås',
    'Örebro', 'Helsingborg', 'Norrköping', 'Jönköping', 'Umeå', 'Lund',
    'Borås', 'Sundsvall', 'Gävle', 'Eskilstuna', 'Halmstad', 'Växjö',
    'Karlstad', 'Kristianstad',
  ],
}
