import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { Plus, ExternalLink, Edit, Trash2, Package, Wrench, Truck } from "lucide-react";
import { syncOrderStatusWithWorkOrders } from "@/hooks/useOrderStatusSync";

interface OrderWorkOrdersManagerProps {
  orderId: string;
  customerId?: string;
  onUpdate: () => void;
}

interface WorkOrder {
  id: string;
  number: string;
  status: string;
  title?: string;
  includes_installation?: boolean;
  bom_id?: string;
  assigned_to?: string;
  priority?: string;
  notes?: string;
  planned_start_date?: string;
  planned_end_date?: string;
}

interface ServiceWorkOrder {
  id: string;
  number: string;
  status: string;
  title?: string;
  description?: string;
  location?: string;
  scheduled_date?: string;
}

interface ShippingOrder {
  id: string;
  number: string;
  status: string;
  notes?: string;
  shipping_address?: string;
}

type WorkOrderType = 'production' | 'service' | 'shipping';

export function OrderWorkOrdersManager({ orderId, customerId, onUpdate }: OrderWorkOrdersManagerProps) {
  const [workOrders, setWorkOrders] = useState<WorkOrder[]>([]);
  const [serviceWorkOrders, setServiceWorkOrders] = useState<ServiceWorkOrder[]>([]);
  const [shippingOrders, setShippingOrders] = useState<ShippingOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [addType, setAddType] = useState<WorkOrderType>('production');
  const [boms, setBoms] = useState<any[]>([]);
  const [technicians, setTechnicians] = useState<any[]>([]);
  const [users, setUsers] = useState<any[]>([]);
  
  const [newWorkOrder, setNewWorkOrder] = useState({
    title: '',
    notes: '',
    bom_id: '',
    assigned_to: '',
    back_office_manager: '',
    priority: 'medium',
    planned_start_date: '',
    planned_end_date: '',
    includes_installation: false,
    // Service specific
    description: '',
    location: '',
    scheduled_date: '',
    // Shipping specific
    shipping_address: ''
  });

  const { toast } = useToast();

  useEffect(() => {
    loadWorkOrders();
    loadRelatedData();
  }, [orderId]);

  const loadWorkOrders = async () => {
    try {
      const [woRes, swoRes, soRes] = await Promise.all([
        supabase.from('work_orders').select('*').eq('sales_order_id', orderId),
        supabase.from('service_work_orders').select('*').eq('sales_order_id', orderId),
        supabase.from('shipping_orders').select('*').eq('sales_order_id', orderId)
      ]);

      if (woRes.error) throw woRes.error;
      if (swoRes.error) throw swoRes.error;
      if (soRes.error) throw soRes.error;

      setWorkOrders(woRes.data || []);
      setServiceWorkOrders(swoRes.data || []);
      setShippingOrders(soRes.data || []);
    } catch (error: any) {
      console.error('Error loading work orders:', error);
      toast({
        title: "Errore",
        description: "Impossibile caricare le commesse",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const loadRelatedData = async () => {
    try {
      const [bomsRes, techniciansRes, usersRes] = await Promise.all([
        supabase.from('boms').select('id, name, version, level').in('level', [0, 1, 2]).order('name'),
        supabase.from('technicians').select('id, first_name, last_name, employee_code').eq('active', true),
        supabase.from('profiles').select('id, email, first_name, last_name').order('first_name')
      ]);

      setBoms(bomsRes.data || []);
      setTechnicians(techniciansRes.data || []);
      setUsers(usersRes.data || []);
    } catch (error) {
      console.error('Error loading related data:', error);
    }
  };

  const handleAddWorkOrder = async () => {
    try {
      if (addType === 'production') {
        const data = {
          number: '', // Auto-generated by DB
          title: newWorkOrder.title || 'Commessa di Produzione',
          status: 'da_fare' as const,
          bom_id: newWorkOrder.bom_id || null,
          customer_id: customerId || null,
          assigned_to: newWorkOrder.assigned_to || null,
          back_office_manager: newWorkOrder.back_office_manager || null,
          priority: newWorkOrder.priority,
          planned_start_date: newWorkOrder.planned_start_date || null,
          planned_end_date: newWorkOrder.planned_end_date || null,
          notes: newWorkOrder.notes || null,
          includes_installation: newWorkOrder.includes_installation,
          sales_order_id: orderId
        };

        const { error } = await supabase.from('work_orders').insert([data]);
        if (error) throw error;
      } else if (addType === 'service') {
        const data = {
          number: '', // Auto-generated by DB
          title: newWorkOrder.title || 'Commessa di Installazione',
          description: newWorkOrder.description || newWorkOrder.notes || null,
          status: 'da_fare' as const,
          customer_id: customerId || null,
          back_office_manager: newWorkOrder.back_office_manager || null,
          priority: newWorkOrder.priority,
          scheduled_date: newWorkOrder.scheduled_date ? new Date(newWorkOrder.scheduled_date).toISOString() : null,
          location: newWorkOrder.location || null,
          notes: newWorkOrder.notes || null,
          sales_order_id: orderId
        };

        const { error } = await supabase.from('service_work_orders').insert([data]);
        if (error) throw error;
      } else if (addType === 'shipping') {
        const data = {
          number: '', // Auto-generated by DB
          status: 'da_preparare' as const,
          back_office_manager: newWorkOrder.back_office_manager || null,
          order_date: new Date().toISOString().split('T')[0],
          notes: newWorkOrder.notes || null,
          shipping_address: newWorkOrder.shipping_address || null,
          sales_order_id: orderId
        };

        const { error } = await supabase.from('shipping_orders').insert([data]);
        if (error) throw error;
      }

      toast({
        title: "Successo",
        description: "Commessa aggiunta con successo"
      });

      setIsAddDialogOpen(false);
      resetForm();
      loadWorkOrders();
      
      // Sincronizza lo stato dell'ordine in base alle commesse
      await syncOrderStatusWithWorkOrders(orderId);
      
      onUpdate();
    } catch (error: any) {
      toast({
        title: "Errore",
        description: "Impossibile aggiungere la commessa: " + error.message,
        variant: "destructive"
      });
    }
  };

  const handleDeleteWorkOrder = async (type: WorkOrderType, id: string) => {
    try {
      const table = type === 'production' ? 'work_orders' : 
                    type === 'service' ? 'service_work_orders' : 'shipping_orders';
      
      const { error } = await supabase.from(table).delete().eq('id', id);
      if (error) throw error;

      toast({
        title: "Successo",
        description: "Commessa eliminata con successo"
      });

      loadWorkOrders();
      
      // Sincronizza lo stato dell'ordine in base alle commesse
      await syncOrderStatusWithWorkOrders(orderId);
      
      onUpdate();
    } catch (error: any) {
      toast({
        title: "Errore",
        description: "Impossibile eliminare la commessa: " + error.message,
        variant: "destructive"
      });
    }
  };

  const resetForm = () => {
    setNewWorkOrder({
      title: '',
      notes: '',
      bom_id: '',
      assigned_to: '',
      back_office_manager: '',
      priority: 'medium',
      planned_start_date: '',
      planned_end_date: '',
      includes_installation: false,
      description: '',
      location: '',
      scheduled_date: '',
      shipping_address: ''
    });
  };

  const getStatusLabel = (status: string): string => {
    const labels: Record<string, string> = {
      'da_fare': 'Da Fare',
      'planned': 'Pianificato',
      'in_progress': 'In Corso',
      'completed': 'Completato',
      'to_do': 'Da Fare',
      'da_preparare': 'Da Preparare',
      'in_preparazione': 'In Preparazione',
      'pronto': 'Pronto',
      'spedito': 'Spedito'
    };
    return labels[status] || status;
  };

  const getStatusColor = (status: string) => {
    if (['completed', 'spedito'].includes(status)) return 'bg-green-100 text-green-800';
    if (['in_progress', 'in_preparazione'].includes(status)) return 'bg-blue-100 text-blue-800';
    if (['pronto'].includes(status)) return 'bg-yellow-100 text-yellow-800';
    return 'bg-gray-100 text-gray-800';
  };

  if (loading) {
    return <div className="text-center py-4 text-muted-foreground">Caricamento commesse...</div>;
  }

  const totalWorkOrders = workOrders.length + serviceWorkOrders.length + shippingOrders.length;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg">Commesse Collegate ({totalWorkOrders})</CardTitle>
          <Button size="sm" onClick={() => setIsAddDialogOpen(true)}>
            <Plus className="w-4 h-4 mr-2" />
            Aggiungi Commessa
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Production Work Orders */}
        {workOrders.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <Package className="w-4 h-4" />
              Commesse di Produzione
            </div>
            {workOrders.map((wo) => (
              <div key={wo.id} className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50">
                <Link 
                  to="/mfg/work-orders"
                  className="flex items-center gap-3 flex-1"
                >
                  <div>
                    <div className="font-medium flex items-center gap-2">
                      {wo.number}
                      <ExternalLink className="w-3 h-3 text-muted-foreground" />
                    </div>
                    {wo.title && <div className="text-sm text-muted-foreground">{wo.title}</div>}
                  </div>
                </Link>
                <div className="flex items-center gap-2">
                  <Badge className={getStatusColor(wo.status)}>
                    {getStatusLabel(wo.status)}
                  </Badge>
                  {wo.includes_installation && (
                    <Badge variant="outline" className="text-xs">+Installazione</Badge>
                  )}
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button variant="ghost" size="icon" className="h-8 w-8">
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>Eliminare la commessa?</AlertDialogTitle>
                        <AlertDialogDescription>
                          Questa azione eliminerà la commessa {wo.number}. L'azione non può essere annullata.
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Annulla</AlertDialogCancel>
                        <AlertDialogAction onClick={() => handleDeleteWorkOrder('production', wo.id)}>
                          Elimina
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Service Work Orders */}
        {serviceWorkOrders.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <Wrench className="w-4 h-4" />
              Commesse di Lavoro/Installazione
            </div>
            {serviceWorkOrders.map((swo) => (
              <div key={swo.id} className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50">
                <Link 
                  to="/support/work-orders"
                  className="flex items-center gap-3 flex-1"
                >
                  <div>
                    <div className="font-medium flex items-center gap-2">
                      {swo.number}
                      <ExternalLink className="w-3 h-3 text-muted-foreground" />
                    </div>
                    {swo.title && <div className="text-sm text-muted-foreground">{swo.title}</div>}
                  </div>
                </Link>
                <div className="flex items-center gap-2">
                  <Badge className={getStatusColor(swo.status)}>
                    {getStatusLabel(swo.status)}
                  </Badge>
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button variant="ghost" size="icon" className="h-8 w-8">
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>Eliminare la commessa?</AlertDialogTitle>
                        <AlertDialogDescription>
                          Questa azione eliminerà la commessa {swo.number}. L'azione non può essere annullata.
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Annulla</AlertDialogCancel>
                        <AlertDialogAction onClick={() => handleDeleteWorkOrder('service', swo.id)}>
                          Elimina
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Shipping Orders */}
        {shippingOrders.length > 0 && (
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <Truck className="w-4 h-4" />
              Commesse di Spedizione
            </div>
            {shippingOrders.map((so) => (
              <div key={so.id} className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50">
                <Link 
                  to="/warehouse/shipping-orders"
                  className="flex items-center gap-3 flex-1"
                >
                  <div>
                    <div className="font-medium flex items-center gap-2">
                      {so.number}
                      <ExternalLink className="w-3 h-3 text-muted-foreground" />
                    </div>
                    {so.shipping_address && <div className="text-sm text-muted-foreground">{so.shipping_address}</div>}
                  </div>
                </Link>
                <div className="flex items-center gap-2">
                  <Badge className={getStatusColor(so.status)}>
                    {getStatusLabel(so.status)}
                  </Badge>
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button variant="ghost" size="icon" className="h-8 w-8">
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>Eliminare la commessa?</AlertDialogTitle>
                        <AlertDialogDescription>
                          Questa azione eliminerà la commessa {so.number}. L'azione non può essere annullata.
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Annulla</AlertDialogCancel>
                        <AlertDialogAction onClick={() => handleDeleteWorkOrder('shipping', so.id)}>
                          Elimina
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </div>
              </div>
            ))}
          </div>
        )}

        {totalWorkOrders === 0 && (
          <div className="text-center py-6 text-muted-foreground">
            Nessuna commessa collegata a questo ordine.
            <br />
            <Button 
              variant="outline" 
              size="sm" 
              className="mt-2"
              onClick={() => setIsAddDialogOpen(true)}
            >
              <Plus className="w-4 h-4 mr-2" />
              Aggiungi la prima commessa
            </Button>
          </div>
        )}
      </CardContent>

      {/* Add Work Order Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Aggiungi Nuova Commessa</DialogTitle>
          </DialogHeader>
          
          <div className="space-y-4">
            <div>
              <Label>Tipo Commessa *</Label>
              <Select value={addType} onValueChange={(v: WorkOrderType) => setAddType(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="production">
                    <div className="flex items-center gap-2">
                      <Package className="w-4 h-4" />
                      Commessa di Produzione (CdP)
                    </div>
                  </SelectItem>
                  <SelectItem value="service">
                    <div className="flex items-center gap-2">
                      <Wrench className="w-4 h-4" />
                      Commessa di Lavoro/Installazione (CdL)
                    </div>
                  </SelectItem>
                  <SelectItem value="shipping">
                    <div className="flex items-center gap-2">
                      <Truck className="w-4 h-4" />
                      Commessa di Spedizione (CdS)
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Titolo</Label>
              <Input
                value={newWorkOrder.title}
                onChange={(e) => setNewWorkOrder({...newWorkOrder, title: e.target.value})}
                placeholder={addType === 'production' ? 'Commessa di Produzione' : 
                             addType === 'service' ? 'Commessa di Installazione' : 'Commessa di Spedizione'}
              />
            </div>

            {/* Production specific fields */}
            {addType === 'production' && (
              <>
                <div>
                  <Label>BOM/Macchinario</Label>
                  <Select 
                    value={newWorkOrder.bom_id} 
                    onValueChange={(v) => setNewWorkOrder({...newWorkOrder, bom_id: v})}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Seleziona BOM" />
                    </SelectTrigger>
                    <SelectContent>
                      {boms.map(bom => (
                        <SelectItem key={bom.id} value={bom.id}>
                          {bom.name} (v{bom.version})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label>Tecnico Assegnato</Label>
                  <Select 
                    value={newWorkOrder.assigned_to} 
                    onValueChange={(v) => setNewWorkOrder({...newWorkOrder, assigned_to: v})}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Seleziona tecnico" />
                    </SelectTrigger>
                    <SelectContent>
                      {technicians.map(tech => (
                        <SelectItem key={tech.id} value={tech.id}>
                          {tech.first_name} {tech.last_name} ({tech.employee_code})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label>Data Inizio Pianificata</Label>
                    <Input
                      type="date"
                      value={newWorkOrder.planned_start_date}
                      onChange={(e) => setNewWorkOrder({...newWorkOrder, planned_start_date: e.target.value})}
                    />
                  </div>
                  <div>
                    <Label>Data Fine Pianificata</Label>
                    <Input
                      type="date"
                      value={newWorkOrder.planned_end_date}
                      onChange={(e) => setNewWorkOrder({...newWorkOrder, planned_end_date: e.target.value})}
                    />
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    id="includes_installation"
                    checked={newWorkOrder.includes_installation}
                    onChange={(e) => setNewWorkOrder({...newWorkOrder, includes_installation: e.target.checked})}
                    className="h-4 w-4 rounded border-gray-300"
                  />
                  <Label htmlFor="includes_installation" className="cursor-pointer">
                    Include installazione
                  </Label>
                </div>
              </>
            )}

            {/* Service specific fields */}
            {addType === 'service' && (
              <>
                <div>
                  <Label>Descrizione Lavoro</Label>
                  <Textarea
                    value={newWorkOrder.description}
                    onChange={(e) => setNewWorkOrder({...newWorkOrder, description: e.target.value})}
                    placeholder="Descrivi il lavoro da eseguire..."
                    rows={3}
                  />
                </div>

                <div>
                  <Label>Luogo</Label>
                  <Input
                    value={newWorkOrder.location}
                    onChange={(e) => setNewWorkOrder({...newWorkOrder, location: e.target.value})}
                    placeholder="Indirizzo o località"
                  />
                </div>

                <div>
                  <Label>Data Programmata</Label>
                  <Input
                    type="date"
                    value={newWorkOrder.scheduled_date}
                    onChange={(e) => setNewWorkOrder({...newWorkOrder, scheduled_date: e.target.value})}
                  />
                </div>
              </>
            )}

            {/* Shipping specific fields */}
            {addType === 'shipping' && (
              <div>
                <Label>Indirizzo di Spedizione</Label>
                <Textarea
                  value={newWorkOrder.shipping_address}
                  onChange={(e) => setNewWorkOrder({...newWorkOrder, shipping_address: e.target.value})}
                  placeholder="Indirizzo completo di spedizione..."
                  rows={3}
                />
              </div>
            )}

            {/* Common fields */}
            <div>
              <Label>Responsabile Back Office</Label>
              <Select 
                value={newWorkOrder.back_office_manager} 
                onValueChange={(v) => setNewWorkOrder({...newWorkOrder, back_office_manager: v})}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Seleziona responsabile" />
                </SelectTrigger>
                <SelectContent>
                  {users.map(user => (
                    <SelectItem key={user.id} value={user.id}>
                      {user.first_name} {user.last_name || user.email}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Priorità</Label>
              <Select 
                value={newWorkOrder.priority} 
                onValueChange={(v) => setNewWorkOrder({...newWorkOrder, priority: v})}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Bassa</SelectItem>
                  <SelectItem value="medium">Media</SelectItem>
                  <SelectItem value="high">Alta</SelectItem>
                  <SelectItem value="urgent">Urgente</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Note</Label>
              <Textarea
                value={newWorkOrder.notes}
                onChange={(e) => setNewWorkOrder({...newWorkOrder, notes: e.target.value})}
                placeholder="Note aggiuntive..."
                rows={3}
              />
            </div>

            <div className="flex justify-end gap-2 pt-4">
              <Button variant="outline" onClick={() => { setIsAddDialogOpen(false); resetForm(); }}>
                Annulla
              </Button>
              <Button onClick={handleAddWorkOrder}>
                Aggiungi Commessa
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
