-- Add external_configurator_link field to leads table to store links from external service
ALTER TABLE leads ADD COLUMN IF NOT EXISTS external_configurator_link TEXT;

-- Add index for better query performance
CREATE INDEX IF NOT EXISTS idx_leads_external_link ON leads(external_configurator_link) WHERE external_configurator_link IS NOT NULL;

-- Add comment to document the field
COMMENT ON COLUMN leads.external_configurator_link IS 'Unique configurator link generated by external service for vesuviano pipeline leads';